server:
  port: 8761

spring:
  application:
    name: discovery-service

  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

eureka:
  instance:
    hostname: ${HOST_NAME}
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${ZONE}