services:
  user-db-postgres:
    image: postgres:latest
    container_name: user-db-postgres
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - user_db_postgres_data:/var/lib/postgresql/data
    networks:
      - user-service-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  user-db-neo4j:
    image: neo4j:5
    container_name: user-db-neo4j
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_memory_heap_max__size: 512M
    ports:
      - "7474:7474"  # Browser
      - "7687:7687"  # Bolt
    volumes:
      - user_db_neo4j_data:/data
      - user_db_neo4j_logs:/logs
    networks:
      - user-service-network
    healthcheck:
      test: [ "CMD-SHELL", "cypher-shell -u neo4j -p password 'RETURN 1'" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  user_db_postgres_data:
    driver: local
  user_db_neo4j_data:
    driver: local
  user_db_neo4j_logs:
    driver: local

networks:
  user-service-network:
    driver: bridge
