server:
  port: 8084

spring:
  application:
    name: feed-service

  grpc:
    client:
      channels:
        user-service:
          address: localhost:${USER_GRPC_SERVER_PORT:9091}
          negotiation-type: plaintext
        post-service:
          address: localhost:${POST_GRPC_SERVER_PORT:9090}
          negotiation-type: plaintext
