server:
  port: 8083

spring:
  application:
    name: interaction-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5435/interactiondb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  grpc:
    server:
      port: ${INTERACTION_GRPC_SERVER_PORT:9092}
    client:
      channels:
        post-service:
          address: localhost:${POST_GRPC_SERVER_PORT:9090}
          negotiation-type: plaintext
        user-service:
          address: localhost:${USER_GRPC_SERVER_PORT:9091}
          negotiation-type: plaintext
