server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/userdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  neo4j:
    uri: ${NEO4J_URL:bolt://localhost:7687}
    authentication:
      username: ${NEO4J_USERNAME:neo4j}
      password: ${NEO4J_PASSWORD:password}
    repositories:
      type: auto

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/social-media}
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://localhost:8180/realms/social-media/protocol/openid-connect/certs}

logging:
  level:
    org.springframework: INFO

keycloak:
  admin:
    server-url: ${KEYCLOAK_ADMIN_URL:http://localhost:8180}
    realm: social-media
    client-id: admin-cli
    admin-username: ${KEYCLOAK_ADMIN_USER:admin}
    admin-password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
